# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - bot-trucho

on:
  push:
    branches:
      - dependabot/npm_and_yarn/hosted-git-info-2.8.9
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_ab387306f6244f19a212b3d502e3a344 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1c7ab82901ec46ad913e18e87d535af6 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ab387306f6244f19a212b3d502e3a344 }}/presi11/discord-bot:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'bot-trucho'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3ddcc044bae949b1b9650cad91ff89c5 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ab387306f6244f19a212b3d502e3a344 }}/presi11/discord-bot:${{ github.sha }}'